### ISSUE TITLE
With Lumen 5.3, just installing the package breaks everything

### ISSUE THREAD

**Issue by BrettTrotter** [ably/ably-php-laravel#1]
I start to get "Class path.storage does not exist" errors as soon as I composer require the ably laravel package. What could I be missing?

**Comment by mattheworiordan** [comment]
Hey @BrettTrotter not sure why no one picked this up before and replied.  Mind if I ask what conclusion you came to?  Would you like one of us to investigate?  Sorry for the delay in response.

**Comment by BrettTrotter** [comment]
I ended up moving on to another platform and upgrading to the full Laravel stack, so I did not put any further time into testing or investigating the errors I was having. May well be ID10T/PEBCAK errors. If no one else reports it, I wouldn't worry about it :)

**Comment by mattheworiordan** [comment]
Ok, thanks for the note.  Shout if we can help in future, not sure why I did not receive the initial notification.
