### ISSUE TITLE
Error code 4001

### ISSUE THREAD

**Issue by falahatiali** [ably/ably-php-laravel#13]
Hi I used following configs but I get an error and this is so weird. 

```java
{"event":"pusher:error","data":{"message":"Malformed key name xxxxx - don't use your secret key, only your keyName (appId.keyId) (Ably error 40101)","code":4001}}
```

- - -
```java
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_ABLY_APP_KEY,
    wsHost: 'realtime-pusher.ably.io',
    wsPort: 443,
    disableStats: true,
    encrypted: true,
});

window.Echo.channel("articles")
    .listen("AblyTestEvent" , (e) => {
     console.log(e);
})
```

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1732) by [Unito](https://www.unito.io)

**Comment by ricocrivelli** [comment]
Set `MIX_ABLY_APP_KEY` in `.env` file only with the public part of your key (bofore the : character).

**Comment by sacOO7** [comment]
I think the code is not relevant with either `ably-php` or `ably-php-laravel`.  More context for the error is needed.

**Comment by sacOO7** [comment]
Seems this error is related to https://github.com/ably/ably-php/issues/150
