### ISSUE TITLE
Customer feature request: 'laravel driver'

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-php-laravel#2]
See [https://app.intercom.io/a/apps/ua39m1ld/respond/inbox/all/conversations/9084030900](https://app.intercom.io/a/apps/ua39m1ld/respond/inbox/all/conversations/9084030900) – customer requesting that we make a 'Laravel driver + Laravel Echo driver' package, which they say would make integration easier

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1737) by [Unito](https://www.unito.io)

**Comment by mattheworiordan** [comment]
Another similar request + advice on what to do:

> I think given how popular Laravel is its worth your investment, Its close to being number 1 framework on github. All you need to add is a broadcast driver for laravel. The documentation is very well documented https://laravel.com/docs/5.4/broadcasting
As you can see Pusher is the default currently.
Once you have broadcasting driver you are pretty much a drop in solution
You would probably want to them add laravel echo support which is the wrapper on the client side

**Comment by Mat-Moo** [comment]
Just joining the party to request this as well. Having my first play with real-time data via sockets etc and keen to explore. Found ably which looks great, but I want a drop in solution that uses broadcasting as laravel has taken me down that route... bit lazy I’ll admit but has the benefit of allowing me to try different things easily. Please consider updating the library to support broadcast. I’m not as bothered about echo, just feels like an unnecessary layer.

**Comment by junaid-A-khan** [comment]
+1. really need its driver for laravel.

**Comment by flearsmedia** [comment]
+1

**Comment by onurkose** [comment]
+1 but I'm not optimistic about this may happen.

**Comment by matthewhall-ca** [comment]
We went ahead and built this Broadcast driver ourselves! 
https://github.com/springboardVR/Laravel-Ably-Broadcaster

**Comment by onurkose** [comment]
> We went ahead and built this Broadcast driver ourselves!
> https://github.com/springboardVR/Laravel-Ably-Broadcaster



> +1 but I'm not optimistic about this may happen.

I'm taking back my words.

I'd changed my mind not now but after talking several hours with Ably support on web chat on 3rd of Sept.

Even their wide range of free solutions were enough for me to run everything I need without paying a penny, support team was amazingly concerned about this implementation and here they are today.

**Comment by sacOO7** [comment]
Currently active PR for the feature open at 
1. https://github.com/laravel/echo/pull/351
2. https://github.com/laravel/docs/pull/8120
3. https://github.com/laravel/framework/pull/43685
4. https://github.com/laravel/echo/pull/351

**Comment by matthewhall-ca** [comment]
This got added to the Laravel core a while ago by Taylor Otwell based on our package https://github.com/springboardVR/Laravel-Ably-Broadcaster

**Comment by sacOO7** [comment]
> This got added to the Laravel core a while ago by Taylor Otwell based on our package https://github.com/springboardVR/Laravel-Ably-Broadcaster

We added official `ably-js` support because we had compatibility issues with `pusher-js`. You can check https://github.com/laravel/docs/pull/8120 and PR description.

**Comment by sacOO7** [comment]
Currently being fixed as a part of #28

**Comment by sacOO7** [comment]
Update :
We have released the official `laravel-broadcaster` ->  https://github.com/ably/laravel-broadcaster. It covers each and every aspect of laravel broadcasting.

**Comment by sacOO7** [comment]
Closing the issue since [official laravel broadcaster ](https://github.com/ably/laravel-broadcaster) is released!
