### ISSUE TITLE
Create Laravel service provider for Ably Broadcaster

### ISSUE THREAD

**Issue by qsdstefan** [ably/ably-php-laravel#28]
Create a service provider as per [official Laravel documentation](https://laravel.com/docs/9.x/providers) to allow integrating Ably Broadcaster as a 3rd party package into Laravel projects.

The supported Laravel versions should be in the range of `6.x` through `9.x`.

Naming scheme:

* Class name: `LaravelAblyBroadcasterServiceProvider`
* Namespace: `Ably\LaravelBroadcaster`
* Broadcaster name: `ably`

**Comment by sacOO7** [comment]
Adding to above tasks 
Update README with different sections
1. Package info, supported laravel version
2. Installation
3. Setup
4. Example code
5. Contributing

**Comment by sacOO7** [comment]
Add GitHub WorkFlow CI like https://github.com/ably/ably-php. Run tests on different `php` versions https://github.com/ably/ably-php/blob/main/.github/workflows/check.yml.

**Comment by sacOO7** [comment]
Also, update the blog https://ably.com/blog/building-a-realtime-chat-app-with-react-laravel-and-websockets with the latest demo code after the package publish.

**Comment by sacOO7** [comment]
We also need to update laravel-echo related old answers after new package is published -> https://faqs.ably.com/is-it-possible-to-prevent-messages-published-being-echoed-back-to-the-publishing-client

**Comment by sacOO7** [comment]
Update https://github.com/ably-labs/laravel-broadcast-app dependencies with published packages.
