### ISSUE TITLE
Laravel 5.5 Support - Auto Discovery

### ISSUE THREAD

**Issue by robbydooo** [ably/ably-php-laravel#3]
Hi,

Can we add Laravel 5.5 support for auto discovery in the composer file please?

I can do a pull request if you like?

Thanks,
Rob

**Comment by mattheworiordan** [comment]
Sorry for the delay @robbydooo. Sure, if you could do a PR we'd be grateful indeed.  We'll send you some Ably swag to say thanks!

**Comment by robbydooo** [comment]
Pull Request submitted.

**Comment by robbydooo** [comment]
Guys this has been in PR for nearly 6 weeks now, is this ever going to get reviewed/approved?

**Comment by mattheworiordan** [comment]
Hi @robbydooo.  I am sorry, I was not notified about that PR for some reason.  I'll get our PHP dev to take a look and comment.

**Comment by mattheworiordan** [comment]
Nudge @jdavid

**Comment by jdavid** [comment]
LGTM

**Comment by mattheworiordan** [comment]
THanks @robbydooo!   Merged. We'll do a release now.

**Comment by robbydooo** [comment]
@mattheworiordan This does not appear to have been pushed to packagist in order for composer updates to pick up version 1.0.2.

Can you publish to packagist please?

**Comment by mattheworiordan** [comment]
Thanks, done @robbydooo
