### ISSUE TITLE
Just install the package and everything is stopped with Lumen 5.6

### ISSUE THREAD

**Issue by meltayeb** [ably/ably-php-laravel#5]
When I have run the command 
`$ composer require ably/ably-php --update-no-dev`

everything in my application not working and give me 500 error 

I think the issue belong to the dependencies cause once I install this package it is removing some packages from my vendor

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1734) by [Unito](https://www.unito.io)

**Comment by Quezler** [comment]
Is there anything relevant in the `./storage/logs/laravel.log`?

**Comment by owenpearson** [comment]
Closing this as stale now
